######################################################################
# Automatically generated by qmake (2.01a) Wed May 17 14:07:49 2017
######################################################################

TEMPLATE = app 
DEPENDPATH += .
INCLUDEPATH += .

DESTDIR = ../bin
TARGET = qt_real_show

OBJECTS_DIR += ../obj

# Input
HEADERS +=  main.h \
            obj_title.h \
            conf.h \
            obj_web.h \
            obj_title_button.h \
            redis_client.h \
            redis_cont.h \
            cpp_datetimer.h \
            radio.h \
            c_md5.h \
            real_cont.h \
            lsystem.h \
            jsonConfFile.h \
            window.h

SOURCES +=  main.cpp \
            obj_title.cpp \
            obj_web.cpp \
            obj_title_button.cpp \
            redis_client.cpp \
            redis_cont.cpp \
            cpp_datetimer.cpp \
            radio.cpp \
            c_md5.cpp \
            real_cont.cpp \
            lsystem.cpp \
            jsonConfFile.cpp \
            window.cpp

QT +=  webkit
LIBS += -ljsoncpp -lhiredis -lsqlite3