#!/bin/sh
. /lib/functions/network.sh







network_get_ipaddr ip lan
network_get_gateway gateway lan
network_get_subnet subnet lan

netmask=${subnet#*/}
network_get_protocol proto lan

echo "{\"ip\":\"${ip}\", \"gateway\":\"${gateway}\", \"netmask\":\"${netmask}\", \"proto\":\"${proto}\"}"
