#!/bin/sh

#百度语音-ACCESS_TOKEN实时获取
python /root/work/baidu_tts/baidu_tts_token/main.py &

#UWSGI服务器
/root/root_bin/uwsgi_pc_install/bin/uwsgi --ini /root/root_bin/uwsgi_pc_install/conf/uwsgi.ini &
/root/root_bin/uwsgi_pc_install/bin/uwsgi --ini /root/root_bin/uwsgi_pc_install/conf/uwsgi_huanjing.ini &

#MQTT服务器
/usr/local/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf -d &

#网易
/root/work/wangyi_music/wangyi_pc /root/work/wangyi_music/db &

#SVN服务器
svnserve -d -r /home/svnrepos --listen-port 8096

#定时任务
/sbin/service crond restart
